export const NAME_DISPLAY = "NAME_DISPLAY";
export const MESSAGE_COUNT = "MESSAGE_COUNT";
export const INVITATIONS_COUNT = "INVITATIONS_COUNT";
export const OTHER_NOTIFICATIONS_COUNT = "OTHER_NOTIFICATIONS_COUNT";
